In [3]:
import numpy as np
np.version.version

'1.16.0'

In [12]:
a = np.random.random((2,3,5))

In [5]:
print(a)

[[[0.77544786 0.90434747 0.25722615 0.63033804 0.69049366]
  [0.72737899 0.84739973 0.42098803 0.68013163 0.23354607]
  [0.35497448 0.36188287 0.57291486 0.70961156 0.16173162]]

 [[0.22384829 0.66639047 0.49519096 0.13869389 0.65658426]
  [0.70972532 0.86914733 0.02263763 0.32828162 0.63700933]
  [0.24717555 0.43764778 0.8203125  0.43624477 0.79859473]]]


In [27]:
b = np.ones((5,2,3))
print(b)
b.shape

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


(5, 2, 3)

In [16]:
b.shape

(5, 2, 3)

In [28]:
c = np.transpose(b, (1,2,0))
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

In [30]:
d = np.add(a,c) 
print(d)

[[[1.75010216 1.92831493 1.83173651 1.22210927 1.12107516]
  [1.86822744 1.68589396 1.22941082 1.66468302 1.34050242]
  [1.04817178 1.38245809 1.95910295 1.28867581 1.8139714 ]]

 [[1.31864327 1.00989033 1.18704768 1.82437382 1.63646677]
  [1.65621358 1.66810585 1.81810086 1.58559326 1.37026343]
  [1.79991724 1.8390663  1.47387651 1.08259352 1.6904948 ]]]


In [31]:
print(a, d)

[[[0.75010216 0.92831493 0.83173651 0.22210927 0.12107516]
  [0.86822744 0.68589396 0.22941082 0.66468302 0.34050242]
  [0.04817178 0.38245809 0.95910295 0.28867581 0.8139714 ]]

 [[0.31864327 0.00989033 0.18704768 0.82437382 0.63646677]
  [0.65621358 0.66810585 0.81810086 0.58559326 0.37026343]
  [0.79991724 0.8390663  0.47387651 0.08259352 0.6904948 ]]] [[[1.75010216 1.92831493 1.83173651 1.22210927 1.12107516]
  [1.86822744 1.68589396 1.22941082 1.66468302 1.34050242]
  [1.04817178 1.38245809 1.95910295 1.28867581 1.8139714 ]]

 [[1.31864327 1.00989033 1.18704768 1.82437382 1.63646677]
  [1.65621358 1.66810585 1.81810086 1.58559326 1.37026343]
  [1.79991724 1.8390663  1.47387651 1.08259352 1.6904948 ]]]


In [50]:
e = np.multiply(a,c)

In [51]:
print(e)

[[[0.75010216 0.92831493 0.83173651 0.22210927 0.12107516]
  [0.86822744 0.68589396 0.22941082 0.66468302 0.34050242]
  [0.04817178 0.38245809 0.95910295 0.28867581 0.8139714 ]]

 [[0.31864327 0.00989033 0.18704768 0.82437382 0.63646677]
  [0.65621358 0.66810585 0.81810086 0.58559326 0.37026343]
  [0.79991724 0.8390663  0.47387651 0.08259352 0.6904948 ]]]


In [68]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9591029541264264
1.0098903313063965
1.5365027645463984


In [82]:
f = np.empty((2,3,5))
f

array([[[0.        , 0.92831493, 0.83173651, 0.22210927, 0.12107516],
        [0.86822744, 0.68589396, 0.22941082, 0.66468302, 0.34050242],
        [0.04817178, 0.38245809, 0.95910295, 0.28867581, 0.8139714 ]],

       [[0.31864327, 0.00989033, 0.18704768, 0.82437382, 0.63646677],
        [0.65621358, 0.66810585, 0.81810086, 0.58559326, 0.37026343],
        [0.79991724, 0.8390663 , 0.47387651, 0.08259352, 0.6904948 ]]])

In [92]:

print(d)
d.shape

[[[1.75010216 1.92831493 1.83173651 1.22210927 1.12107516]
  [1.86822744 1.68589396 1.22941082 1.66468302 1.34050242]
  [1.04817178 1.38245809 1.95910295 1.28867581 1.8139714 ]]

 [[1.31864327 1.00989033 1.18704768 1.82437382 1.63646677]
  [1.65621358 1.66810585 1.81810086 1.58559326 1.37026343]
  [1.79991724 1.8390663  1.47387651 1.08259352 1.6904948 ]]]


(2, 3, 5)

In [97]:
aux1 = 0
aux2 = 0
aux3 = 0
for first in d:        
    aux2 = 0
    for second in first:
        aux3 = 0
        for x in second:           
            
            if x == d_min:
                f[aux1][aux2][aux3] = "A"
            elif x == d_max:
                f[aux1][aux2][aux3] = "E"
            elif x == d_mean:
                f[aux1][aux2][aux3] = "C"
            elif x >= d_mean:
                f[aux1][aux2][aux3] = "D"
            else:
                f[aux1][aux2][aux3] = "B"
            
            aux3 +=1
            
            
    
        aux2 +=1
    
    aux1 += 1  


[[[ 75.  75.  75.  25.  25.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25. 100.  25.  75.]]

 [[ 25.   0.  25.  75.  75.]
  [ 75.  75.  75.  75.  25.]
  [ 75.  75.  25.  25.  75.]]]


In [73]:
for x in np.nditer(d):
    if x == d_min:
        f = np.append(f, [0], axis=0)
    elif x == d_max:
        f = np.append(f, [100], axis=0)
        

TypeError: append() missing 1 required positional argument: 'values'

In [79]:
f[0][0][0] = 0


[[[0.         0.92831493 0.83173651 0.22210927 0.12107516]
  [0.86822744 0.68589396 0.22941082 0.66468302 0.34050242]
  [0.04817178 0.38245809 0.95910295 0.28867581 0.8139714 ]]

 [[0.31864327 0.00989033 0.18704768 0.82437382 0.63646677]
  [0.65621358 0.66810585 0.81810086 0.58559326 0.37026343]
  [0.79991724 0.8390663  0.47387651 0.08259352 0.6904948 ]]]


In [98]:
print(d)
print(f)

[[[1.75010216 1.92831493 1.83173651 1.22210927 1.12107516]
  [1.86822744 1.68589396 1.22941082 1.66468302 1.34050242]
  [1.04817178 1.38245809 1.95910295 1.28867581 1.8139714 ]]

 [[1.31864327 1.00989033 1.18704768 1.82437382 1.63646677]
  [1.65621358 1.66810585 1.81810086 1.58559326 1.37026343]
  [1.79991724 1.8390663  1.47387651 1.08259352 1.6904948 ]]]
[[[ 75.  75.  75.  25.  25.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25. 100.  25.  75.]]

 [[ 25.   0.  25.  75.  75.]
  [ 75.  75.  75.  75.  25.]
  [ 75.  75.  25.  25.  75.]]]


In [99]:
aux1 = 0
aux2 = 0
aux3 = 0
for first in d:        
    aux2 = 0
    for second in first:
        aux3 = 0
        for x in second:           
            
            if x == d_min:
                f[aux1][aux2][aux3] = "A"
            elif x == d_max:
                f[aux1][aux2][aux3] = "E"
            elif x == d_mean:
                f[aux1][aux2][aux3] = "C"
            elif x >= d_mean:
                f[aux1][aux2][aux3] = "D"
            else:
                f[aux1][aux2][aux3] = "B"
            
            aux3 +=1
            
            
    
        aux2 +=1
    
    aux1 += 1  

ValueError: could not convert string to float: 'D'